import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Muhammad Sameer Amjad | Computer Scientist',
  description:
    "Hi, I'm Sameer, a junior at NUST, Islamabad passionate about LLMs, 6G technology (RIS), and crafting amazing Apps. My focus is NEXT.js, Flutter, React Native, TypeScript, and AWS, with a love for research and literature.",
  keywords: [
    'Sameer Amjad',
    'Computer Scientist',
    'Web Developer',
    'NUST',
    'LLMs',
    '6G Technology',
    'RIS',
    'TypeScript',
    'AWS',
    'Research',
    'Front-end',
    'Portfolio',
    'Projects',
    'Web Applications',
    'Tech Enthusiast',
    'Programming',
    'Literature',
    'Pakistan',
    'React',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Website',
    'Developer',
    'Code',
    'Programming',
  ],
  url: env.SITE_URL || 'https://example.com',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
